name: Docker Build/Publish Image 
on:  
  push:    
    branches: [ master ]
    tags: 
      - "v*.*.*"
jobs:   
  build:    
    runs-on: ubuntu-latest
    env:      
      DOCKER_IMAGE: yanqinghao/just4fun
      DOCKER_TARGET_PLATFORM: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x

    steps:    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v3

    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Run Buildx (push image)
      if: success()
      run: |        
        docker buildx build \
          --platform ${DOCKER_TARGET_PLATFORM} \
          --tag ${DOCKER_IMAGE}:latest ${DOCKER_IMAGE}:${GITHUB_RUN_NUMBER} ${DOCKER_IMAGE}:${{ steps.get_version.outputs.VERSION }} \
          --file ./docker/amd64/Dockerfile \
          --output "type=image,push=true" .
